version: "3"
services:
        redis:
                image: redis
                ports:
                        - "6379:6379"
                volumes:
                        - "/home/docker/data:/data"
                networks:
                        - webnet
        db:
                image: postgres
                ports:
                        - "5432:5432"
                volumes:
                        - ./postgres-data:/var/lib/postgresql/data
                environment:
                        POSTGRES_PASSWORD: somePass
                networks:
                        - webnet
        rabbitmq:
                image: rabbitmq:3-management
                ports:
                        - 15672:15672
                        - 5672:5672
                hostname: my-rabbit
                environment:
                        - RABBITMQ_DEFAULT_USER=aleUser
                        - RABBITMQ_DEFAULT_PASS=alePass
                networks:
                        - webnet
        back:
                image: javaservice
                ports: 
                        - "4001:8080"
                networks:
                        - webnet
networks:
        webnet:
