version: "3"
services:
        redis:
                image: redis
                ports:
                        - "6379:6379"
                volumes:
                        - "/home/docker/data:/data"
                networks:
                        - webnet
        db:
                image: postgres
                ports:
                        - "5432:5432"
                volumes:
                        - ./postgres-data:/var/lib/postgresql/data
                environment:
                        POSTGRES_PASSWORD: somePass
                networks:
                        - webnet
networks:
        webnet:
